### ISSUE TITLE
BUG NA HORA DE ACEITAR PAGAMENTO

### ISSUE THREAD

**Issue by ChavosoDEV** [Overx/viperpro#2]

**Comment by Overx** [comment]
Está faltando a rota, verifica por favor em routes\groups\gateways\digitopay.php

Se tem a rota, se não tiver coloque. Não esqueça de verificar se tem o middleware admin, isso evita os espertinho de tentar sacar pelo painel de afiliado.

Route::middleware(['admin.filament', 'admin'])
            ->group(function ()
            {
                Route::get('withdrawal/{id}/{action}', [DigitoPayController::class, 'withdrawalFromModal'])->name('digitopay.withdrawal');
                Route::get('cancelwithdrawal/{id}/{action}', [DigitoPayController::class, 'cancelWithdrawalFromModal'])->name('digitopay.cancelwithdrawal');
            });

**Comment by ChavosoDEV** [comment]
![image](https://github.com/Overx/viperpro/assets/111409421/907b5e69-1a1e-4afc-89d4-587d8767917a)

coloquei oque você informou, mais apareceu um novo erro

**Comment by ChavosoDEV** [comment]
criei a tabela no banco de dados, porem quando eu clico em aceitar pagamento aparece pra confirmar tudo ok, mais quando eu confirmo aparece que deu erro no saque

![image](https://github.com/Overx/viperpro/assets/111409421/8ea35523-395a-4f66-9c70-25a6d1c10517)

**Comment by ChavosoDEV** [comment]
depositar ta tudo ok, agora so o saque que ta dando erro,
