### ISSUE TITLE
Tenho uma duvida 

### ISSUE THREAD

**Issue by Dhjs9w99aiBke** [Overx/viperpro#7]
A minha duvida é.quando o cara apostar e perde o dinheiro no viper pro 1.50 vai para o gateway de pagamento que é a digito pay.

**Comment by Overx** [comment]
De fato, você utiliza sua própria chave na plataforma. Este projeto não envolve split ou GGR. Quanto à Digitopay, pode ficar tranquilo, pois eles não permitem a configuração de split diretamente pelo código; qualquer solicitação desse tipo deve ser feita diretamente ao suporte.

**Comment by Dhjs9w99aiBke** [comment]
Então o dinheiro perdido vai para o gateway de pagamento
